#!/bin/bash
# Swappiness Configuration Script
# Optimizes swap behavior for HPC/ML workloads
# Target: Ubuntu 22.04 LTS

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_section() { echo -e "${BLUE}[====]${NC} $1"; }

# Check root privileges
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

print_section "Memory Swappiness Configuration Utility"
echo

# Display current configuration
print_info "Current Memory Configuration:"
echo "  Swappiness: $(cat /proc/sys/vm/swappiness)"
echo "  Cache Pressure: $(cat /proc/sys/vm/vfs_cache_pressure)"
echo "  Dirty Ratio: $(cat /proc/sys/vm/dirty_ratio)"
echo "  Dirty Background Ratio: $(cat /proc/sys/vm/dirty_background_ratio)"
echo

# Display swap information
print_info "Current Swap Status:"
swapon --show || print_warn "No swap configured"
free -h | grep -E "(Mem|Swap)"
echo

# Default values optimized for ML workloads
SWAPPINESS=${1:-10}           # Low swappiness for memory-intensive workloads
CACHE_PRESSURE=${2:-50}       # Default cache pressure
DIRTY_RATIO=${3:-10}          # Dirty page ratio
DIRTY_BG_RATIO=${4:-5}        # Background dirty ratio

print_info "Applying Configuration:"
echo "  Swappiness: $SWAPPINESS (default=60, lower=less swap)"
echo "  Cache Pressure: $CACHE_PRESSURE (default=100)"
echo "  Dirty Ratio: $DIRTY_RATIO% (default=20)"
echo "  Dirty Background Ratio: $DIRTY_BG_RATIO% (default=10)"
echo

# Apply settings
print_info "Applying runtime settings..."
sysctl -w vm.swappiness=$SWAPPINESS
sysctl -w vm.vfs_cache_pressure=$CACHE_PRESSURE
sysctl -w vm.dirty_ratio=$DIRTY_RATIO
sysctl -w vm.dirty_background_ratio=$DIRTY_BG_RATIO

# Additional memory management settings for HPC/ML
print_info "Applying additional memory optimizations..."
sysctl -w vm.min_free_kbytes=262144           # Minimum free memory (256MB)
sysctl -w vm.zone_reclaim_mode=0              # Disable zone reclaim
sysctl -w vm.overcommit_memory=1              # Allow overcommit
sysctl -w kernel.shmmax=68719476736           # Max shared memory (64GB)
sysctl -w kernel.shmall=16777216              # Max shared memory pages

# Make changes persistent
print_info "Making changes persistent..."

SYSCTL_CONF="/etc/sysctl.d/99-ml-memory-optimization.conf"

cat > "$SYSCTL_CONF" << EOF
# Memory Optimization for HPC/ML Workloads
# Generated by configure-swappiness.sh on $(date)
# Target: Ubuntu 22.04 LTS with NVIDIA RTX 4080

# Swappiness - reduce swap usage (0-100, lower = less swap)
vm.swappiness=$SWAPPINESS

# VFS cache pressure
vm.vfs_cache_pressure=$CACHE_PRESSURE

# Dirty page ratios
vm.dirty_ratio=$DIRTY_RATIO
vm.dirty_background_ratio=$DIRTY_BG_RATIO

# Additional memory settings
vm.min_free_kbytes=262144
vm.zone_reclaim_mode=0
vm.overcommit_memory=1

# Shared memory limits
kernel.shmmax=68719476736
kernel.shmall=16777216

# Network tuning for InfiniBand/RDMA
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.ipv4.tcp_rmem=4096 87380 67108864
net.ipv4.tcp_wmem=4096 65536 67108864

# File system tuning
fs.file-max=2097152
fs.aio-max-nr=1048576
EOF

print_info "Configuration saved to: $SYSCTL_CONF"

# Apply from file to verify
sysctl -p "$SYSCTL_CONF"

# Configure ZRAM (optional compressed swap in RAM)
print_section "ZRAM Configuration (Optional)"
read -p "Do you want to enable ZRAM (compressed swap in RAM)? [y/N]: " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_info "Installing and configuring ZRAM..."

    apt-get update
    apt-get install -y zram-config zram-tools

    # Configure ZRAM size (50% of RAM)
    cat > /etc/default/zramswap << 'EOF'
# Compression algorithm (lzo, lz4, zstd)
ALGO=zstd

# Percentage of RAM to use for ZRAM (default 50%)
PERCENT=50

# Priority (higher = preferred)
PRIORITY=100
EOF

    systemctl restart zramswap.service
    print_info "ZRAM enabled and configured"
    swapon --show
fi

# Display final configuration
echo
print_section "Final Configuration"
print_info "Runtime Settings:"
sysctl vm.swappiness vm.vfs_cache_pressure vm.dirty_ratio vm.dirty_background_ratio

echo
print_info "Memory Status:"
free -h

echo
print_info "Swap Status:"
swapon --show

echo
print_section "Configuration Complete!"
print_info "Settings have been applied and will persist across reboots."
print_info "Configuration file: $SYSCTL_CONF"
echo

# Recommendations
print_section "Recommendations"
echo "Swappiness Values:"
echo "  0   - Swap only when absolutely necessary"
echo "  10  - Recommended for ML/AI workloads (current setting)"
echo "  60  - Default Ubuntu value"
echo "  100 - Swap aggressively"
echo
echo "For memory-intensive workloads (LLM inference, training):"
echo "  - Use swappiness=0 to 10"
echo "  - Ensure sufficient physical RAM"
echo "  - Monitor with: watch -n1 free -h"
echo "  - Consider ZRAM for compressed swap"
