#!/bin/bash
# Kernel Optimization Script for HPC/ML Workloads
# Optimizes Ubuntu 22.04 for NVIDIA RTX 4080 and ML workloads
# Target: Ubuntu 22.04 LTS

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_section() { echo -e "${BLUE}[====]${NC} $1"; }

# Check root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

print_section "Ubuntu 22.04 Kernel Optimization for HPC/ML"
echo

# Display system information
print_info "System Information:"
echo "  Kernel: $(uname -r)"
echo "  Distribution: $(lsb_release -d | cut -f2)"
echo "  CPU: $(lscpu | grep "Model name" | cut -d: -f2 | xargs)"
echo "  Memory: $(free -h | grep Mem | awk '{print $2}')"
echo "  GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo 'Not detected')"
echo

# Update system
print_section "Step 1: System Update"
print_info "Updating package lists..."
apt-get update

print_info "Upgrading system packages..."
apt-get upgrade -y

# Install essential tools
print_section "Step 2: Installing Essential Tools"
ESSENTIAL_PACKAGES=(
    build-essential
    linux-headers-$(uname -r)
    dkms
    cmake
    git
    htop
    iotop
    sysstat
    numactl
    hwloc
    cpufrequtils
    tuned
    tuned-utils
)

print_info "Installing packages: ${ESSENTIAL_PACKAGES[*]}"
apt-get install -y "${ESSENTIAL_PACKAGES[@]}"

# Install monitoring tools
print_info "Installing monitoring and profiling tools..."
apt-get install -y \
    linux-tools-common \
    linux-tools-$(uname -r) \
    trace-cmd \
    kernelshark \
    perf-tools-unstable \
    sysfsutils

# CPU Governor Configuration
print_section "Step 3: CPU Governor Configuration"
print_info "Current CPU governor:"
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

print_info "Setting CPU governor to 'performance'..."
for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    echo performance > "$cpu" 2>/dev/null || true
done

# Make persistent
cat > /etc/systemd/system/cpu-performance.service << 'EOF'
[Unit]
Description=Set CPU governor to performance mode
DefaultDependencies=no
After=sysinit.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance > $cpu 2>/dev/null || true; done'

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable cpu-performance.service
systemctl start cpu-performance.service

print_info "CPU governor set to performance"

# Kernel Parameters Optimization
print_section "Step 4: Kernel Parameters Optimization"

KERNEL_CONF="/etc/sysctl.d/99-hpc-ml-optimization.conf"

print_info "Creating optimized kernel configuration..."
cat > "$KERNEL_CONF" << 'EOF'
# HPC/ML Kernel Optimization
# Target: Ubuntu 22.04 LTS with NVIDIA RTX 4080
# Generated by optimize-kernel.sh

# ===== CPU Scheduler =====
# Reduce scheduler migration cost for better cache locality
kernel.sched_migration_cost_ns=5000000
kernel.sched_autogroup_enabled=0
kernel.sched_latency_ns=6000000
kernel.sched_min_granularity_ns=750000
kernel.sched_wakeup_granularity_ns=1000000

# ===== Memory Management =====
vm.swappiness=10
vm.dirty_ratio=10
vm.dirty_background_ratio=5
vm.vfs_cache_pressure=50
vm.min_free_kbytes=262144
vm.zone_reclaim_mode=0
vm.overcommit_memory=1

# ===== Huge Pages =====
vm.nr_hugepages=1024
vm.hugetlb_shm_group=0

# ===== Network Performance =====
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.core.rmem_default=16777216
net.core.wmem_default=16777216
net.core.optmem_max=40960
net.core.netdev_max_backlog=50000
net.ipv4.tcp_rmem=4096 87380 67108864
net.ipv4.tcp_wmem=4096 65536 67108864
net.ipv4.tcp_max_syn_backlog=30000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fin_timeout=15
net.ipv4.tcp_keepalive_time=300
net.ipv4.tcp_keepalive_probes=5
net.ipv4.tcp_keepalive_intvl=15

# ===== File System =====
fs.file-max=2097152
fs.aio-max-nr=1048576
fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=512

# ===== Shared Memory =====
kernel.shmmax=68719476736
kernel.shmall=16777216
kernel.msgmnb=65536
kernel.msgmax=65536

# ===== Security (relaxed for performance) =====
kernel.yama.ptrace_scope=0

# ===== System Limits =====
kernel.pid_max=4194304
kernel.threads-max=4194304
vm.max_map_count=262144
EOF

print_info "Applying kernel parameters..."
sysctl -p "$KERNEL_CONF"

# Configure system limits
print_section "Step 5: System Limits Configuration"

LIMITS_CONF="/etc/security/limits.d/99-ml-limits.conf"

print_info "Configuring system limits..."
cat > "$LIMITS_CONF" << 'EOF'
# System Limits for HPC/ML Workloads
# /etc/security/limits.d/99-ml-limits.conf

# Core dumps
*       soft    core            unlimited
*       hard    core            unlimited

# Max file descriptors
*       soft    nofile          1048576
*       hard    nofile          1048576

# Max processes
*       soft    nproc           unlimited
*       hard    nproc           unlimited

# Max locked memory (important for GPU/RDMA)
*       soft    memlock         unlimited
*       hard    memlock         unlimited

# Stack size
*       soft    stack           unlimited
*       hard    stack           unlimited

# CPU time
*       soft    cpu             unlimited
*       hard    cpu             unlimited

# Max memory
*       soft    rss             unlimited
*       hard    rss             unlimited
EOF

print_info "System limits configured"

# GRUB Configuration
print_section "Step 6: GRUB Bootloader Configuration"

print_info "Current GRUB configuration:"
grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub

GRUB_PARAMS="transparent_hugepage=never numa_balancing=disable intel_pstate=disable processor.max_cstate=1 intel_idle.max_cstate=0"

if ! grep -q "$GRUB_PARAMS" /etc/default/grub; then
    print_info "Adding optimized kernel parameters to GRUB..."

    # Backup original grub config
    cp /etc/default/grub /etc/default/grub.backup

    # Add parameters
    sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"$GRUB_PARAMS /" /etc/default/grub

    # Update grub
    update-grub

    print_info "GRUB configuration updated"
    print_warn "Reboot required for GRUB changes to take effect"
else
    print_info "GRUB already optimized"
fi

# Install and configure tuned
print_section "Step 7: Tuned Profile Configuration"

print_info "Creating custom tuned profile for ML workloads..."
mkdir -p /etc/tuned/ml-performance

cat > /etc/tuned/ml-performance/tuned.conf << 'EOF'
[main]
summary=Optimized for Machine Learning and HPC workloads
include=throughput-performance

[cpu]
governor=performance
energy_perf_bias=performance
min_perf_pct=100

[sysctl]
vm.swappiness=10
vm.dirty_ratio=10
vm.dirty_background_ratio=5
kernel.sched_migration_cost_ns=5000000

[vm]
transparent_hugepages=never

[disk]
readahead=>4096
EOF

print_info "Activating tuned profile..."
tuned-adm profile ml-performance

# IRQ Affinity for GPU
print_section "Step 8: IRQ Affinity Configuration (Optional)"

if command -v nvidia-smi &> /dev/null; then
    print_info "NVIDIA GPU detected, configuring IRQ affinity..."

    # This script will need to be run after each boot
    cat > /usr/local/bin/set-gpu-irq-affinity.sh << 'EOF'
#!/bin/bash
# Set IRQ affinity for NVIDIA GPU
# Bind GPU interrupts to specific CPU cores for better performance

# Find NVIDIA GPU IRQs
for irq in $(grep nvidia /proc/interrupts | awk '{print $1}' | sed 's/://'); do
    # Set affinity to cores 0-3 (adjust based on your CPU topology)
    echo "Setting IRQ $irq affinity to cores 0-3"
    echo "0f" > /proc/irq/$irq/smp_affinity
done
EOF

    chmod +x /usr/local/bin/set-gpu-irq-affinity.sh
    /usr/local/bin/set-gpu-irq-affinity.sh

    print_info "GPU IRQ affinity configured"
else
    print_warn "NVIDIA GPU not detected, skipping IRQ affinity setup"
fi

# Create verification script
print_section "Step 9: Creating Verification Script"

cat > /usr/local/bin/verify-kernel-optimization.sh << 'EOF'
#!/bin/bash
echo "===== Kernel Optimization Status ====="
echo
echo "CPU Governor:"
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo
echo "Transparent Huge Pages:"
cat /sys/kernel/mm/transparent_hugepage/enabled
echo
echo "Swappiness:"
sysctl vm.swappiness
echo
echo "CPU Frequency:"
lscpu | grep MHz
echo
echo "Tuned Profile:"
tuned-adm active
echo
echo "System Limits (max open files):"
ulimit -n
echo
echo "Memory Info:"
free -h
echo
echo "GPU Status:"
nvidia-smi --query-gpu=name,driver_version,temperature.gpu,utilization.gpu,utilization.memory --format=csv 2>/dev/null || echo "NVIDIA GPU not detected"
EOF

chmod +x /usr/local/bin/verify-kernel-optimization.sh

# Summary
print_section "Optimization Complete!"
echo
print_info "Summary of Changes:"
echo "  ✓ System packages updated"
echo "  ✓ Essential tools installed"
echo "  ✓ CPU governor set to 'performance'"
echo "  ✓ Kernel parameters optimized"
echo "  ✓ System limits increased"
echo "  ✓ GRUB configuration updated"
echo "  ✓ Tuned profile activated: ml-performance"
echo "  ✓ Verification script created"
echo
print_info "Configuration Files:"
echo "  - Kernel params: $KERNEL_CONF"
echo "  - System limits: $LIMITS_CONF"
echo "  - Tuned profile: /etc/tuned/ml-performance/"
echo "  - Verification: /usr/local/bin/verify-kernel-optimization.sh"
echo
print_warn "IMPORTANT: Reboot required for all changes to take full effect"
echo
print_info "To verify optimization status, run:"
echo "  sudo /usr/local/bin/verify-kernel-optimization.sh"
echo
read -p "Do you want to reboot now? [y/N]: " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_info "Rebooting system..."
    reboot
else
    print_info "Please remember to reboot when convenient"
fi
